package com.lockerroom.face.utils;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

public class AssetUtils {

    public static List<String> lstHairFaces() {
        List<String> arrayList = new ArrayList<>();
        arrayList.add("sticker/eye/1.webp");
        arrayList.add("sticker/eye/2.webp");
        arrayList.add("sticker/eye/3.webp");
        arrayList.add("sticker/eye/4.webp");
        arrayList.add("sticker/eye/5.webp");
        arrayList.add("sticker/eye/6.webp");
        arrayList.add("sticker/eye/7.webp");
        arrayList.add("sticker/eye/8.webp");
        arrayList.add("sticker/eye/9.webp");
        arrayList.add("sticker/eye/10.webp");
        arrayList.add("sticker/eye/11.webp");
        arrayList.add("sticker/eye/12.webp");
        arrayList.add("sticker/eye/13.webp");
        arrayList.add("sticker/eye/14.webp");
        arrayList.add("sticker/eye/15.webp");
        arrayList.add("sticker/eye/16.webp");
        arrayList.add("sticker/eye/17.webp");
        arrayList.add("sticker/eye/18.webp");
        arrayList.add("sticker/eye/19.webp");
        arrayList.add("sticker/eye/20.webp");
        arrayList.add("sticker/eye/21.webp");
        arrayList.add("sticker/eye/22.webp");
        arrayList.add("sticker/eye/23.webp");
        arrayList.add("sticker/eye/24.webp");
        arrayList.add("sticker/eye/25.webp");
        arrayList.add("sticker/eye/26.webp");
        arrayList.add("sticker/eye/27.webp");
        arrayList.add("sticker/eye/28.webp");
        arrayList.add("sticker/eye/29.webp");
        arrayList.add("sticker/eye/30.webp");
        arrayList.add("sticker/eye/31.webp");
        arrayList.add("sticker/eye/32.webp");
        arrayList.add("sticker/eye/33.webp");
        arrayList.add("sticker/eye/34.webp");
        arrayList.add("sticker/eye/35.webp");
        arrayList.add("sticker/eye/36.webp");
        arrayList.add("sticker/eye/37.webp");
        arrayList.add("sticker/eye/38.webp");
        arrayList.add("sticker/eye/39.webp");
        arrayList.add("sticker/eye/40.webp");
        arrayList.add("sticker/eye/41.webp");
        arrayList.add("sticker/eye/42.webp");
        arrayList.add("sticker/eye/43.webp");

        return arrayList;
    }

    public static List<String> lstCatFaces() {
        List<String> arrayList = new ArrayList<>();

        arrayList.add("sticker/cat/01.webp");
        arrayList.add("sticker/cat/02.webp");
        arrayList.add("sticker/cat/03.webp");
        arrayList.add("sticker/cat/04.webp");
        arrayList.add("sticker/cat/05.webp");
        arrayList.add("sticker/cat/06.webp");
        arrayList.add("sticker/cat/07.webp");
        arrayList.add("sticker/cat/08.webp");
        arrayList.add("sticker/cat/09.webp");
        arrayList.add("sticker/cat/10.webp");
        arrayList.add("sticker/cat/11.webp");
        arrayList.add("sticker/cat/12.webp");
        arrayList.add("sticker/cat/13.webp");
        arrayList.add("sticker/cat/14.webp");
        arrayList.add("sticker/cat/15.webp");
        arrayList.add("sticker/cat/16.webp");
        arrayList.add("sticker/cat/17.webp");
        arrayList.add("sticker/cat/18.webp");
        arrayList.add("sticker/cat/19.webp");
        arrayList.add("sticker/cat/20.webp");
        arrayList.add("sticker/cat/21.webp");
        arrayList.add("sticker/cat/22.webp");
        arrayList.add("sticker/cat/23.webp");
        arrayList.add("sticker/cat/24.webp");
        arrayList.add("sticker/cat/25.webp");
        arrayList.add("sticker/cat/26.webp");
        arrayList.add("sticker/cat/27.webp");
        arrayList.add("sticker/cat/28.webp");
        arrayList.add("sticker/cat/29.webp");
        arrayList.add("sticker/cat/30.webp");
        arrayList.add("sticker/cat/31.webp");
        arrayList.add("sticker/cat/32.webp");
        arrayList.add("sticker/cat/33.webp");
        arrayList.add("sticker/cat/34.webp");
        arrayList.add("sticker/cat/35.webp");
        arrayList.add("sticker/cat/36.webp");
        arrayList.add("sticker/cat/37.webp");
        arrayList.add("sticker/cat/38.webp");
        arrayList.add("sticker/cat/39.webp");
        arrayList.add("sticker/cat/40.webp");
        arrayList.add("sticker/cat/41.webp");
        arrayList.add("sticker/cat/45.webp");
        arrayList.add("sticker/cat/46.webp");
        arrayList.add("sticker/cat/47.webp");
        arrayList.add("sticker/cat/48.webp");
        arrayList.add("sticker/cat/49.webp");
        arrayList.add("sticker/cat/50.webp");
        arrayList.add("sticker/cat/51.webp");
        arrayList.add("sticker/cat/52.webp");
        arrayList.add("sticker/cat/53.webp");
        arrayList.add("sticker/cat/54.webp");
        arrayList.add("sticker/cat/55.webp");
        arrayList.add("sticker/cat/56.webp");
        return arrayList;
    }

    public static List<String> lstCkeeks() {
        List<String> arrayList = new ArrayList<>();
        arrayList.add("sticker/cheek/01.webp");
        arrayList.add("sticker/cheek/02.webp");
        arrayList.add("sticker/cheek/03.webp");
        arrayList.add("sticker/cheek/04.webp");
        arrayList.add("sticker/cheek/05.webp");
        arrayList.add("sticker/cheek/06.webp");
        arrayList.add("sticker/cheek/07.webp");
        arrayList.add("sticker/cheek/08.webp");
        arrayList.add("sticker/cheek/09.webp");
        arrayList.add("sticker/cheek/10.webp");
        arrayList.add("sticker/cheek/11.webp");
        arrayList.add("sticker/cheek/12.webp");
        arrayList.add("sticker/cheek/13.webp");
        arrayList.add("sticker/cheek/14.webp");
        arrayList.add("sticker/cheek/15.webp");
        arrayList.add("sticker/cheek/16.webp");
        arrayList.add("sticker/cheek/17.webp");
        arrayList.add("sticker/cheek/18.webp");
        arrayList.add("sticker/cheek/19.webp");
        arrayList.add("sticker/cheek/20.webp");
        arrayList.add("sticker/cheek/21.webp");
        arrayList.add("sticker/cheek/22.webp");
        arrayList.add("sticker/cheek/23.webp");
        arrayList.add("sticker/cheek/24.webp");
        arrayList.add("sticker/cheek/25.webp");
        arrayList.add("sticker/cheek/26.webp");
        arrayList.add("sticker/cheek/27.webp");
        arrayList.add("sticker/cheek/28.webp");
        arrayList.add("sticker/cheek/29.webp");
        arrayList.add("sticker/cheek/30.webp");
        arrayList.add("sticker/cheek/31.webp");
        arrayList.add("sticker/cheek/32.webp");
        arrayList.add("sticker/cheek/33.webp");
        arrayList.add("sticker/cheek/34.webp");
        arrayList.add("sticker/cheek/35.webp");
        arrayList.add("sticker/cheek/36.webp");
        arrayList.add("sticker/cheek/37.webp");
        arrayList.add("sticker/cheek/38.webp");
        arrayList.add("sticker/cheek/39.webp");
        arrayList.add("sticker/cheek/40.webp");
        arrayList.add("sticker/cheek/41.webp");
        arrayList.add("sticker/cheek/42.webp");
        arrayList.add("sticker/cheek/43.webp");
        arrayList.add("sticker/cheek/44.webp");
        arrayList.add("sticker/cheek/45.webp");
        arrayList.add("sticker/cheek/46.webp");
        arrayList.add("sticker/cheek/47.webp");
        return arrayList;
    }

    public static List<String> lstGlasses() {
        List<String> arrayList = new ArrayList<>();
        arrayList.add("sticker/glasses/01.webp");
        arrayList.add("sticker/glasses/02.webp");
        arrayList.add("sticker/glasses/03.webp");
        arrayList.add("sticker/glasses/04.webp");
        arrayList.add("sticker/glasses/05.webp");
        arrayList.add("sticker/glasses/06.webp");
        arrayList.add("sticker/glasses/07.webp");
        arrayList.add("sticker/glasses/08.webp");
        arrayList.add("sticker/glasses/09.webp");
        arrayList.add("sticker/glasses/10.webp");
        arrayList.add("sticker/glasses/11.webp");
        arrayList.add("sticker/glasses/12.webp");
        arrayList.add("sticker/glasses/13.webp");
        arrayList.add("sticker/glasses/14.webp");
        arrayList.add("sticker/glasses/15.webp");
        arrayList.add("sticker/glasses/16.webp");
        arrayList.add("sticker/glasses/17.webp");
        arrayList.add("sticker/glasses/18.webp");
        arrayList.add("sticker/glasses/19.webp");
        arrayList.add("sticker/glasses/20.webp");
        arrayList.add("sticker/glasses/21.webp");
        arrayList.add("sticker/glasses/22.webp");
        arrayList.add("sticker/glasses/23.webp");
        arrayList.add("sticker/glasses/24.webp");
        arrayList.add("sticker/glasses/25.webp");
        arrayList.add("sticker/glasses/26.webp");
        arrayList.add("sticker/glasses/27.webp");
        arrayList.add("sticker/glasses/28.webp");
        arrayList.add("sticker/glasses/29.webp");
        arrayList.add("sticker/glasses/30.webp");
        arrayList.add("sticker/glasses/31.webp");
        arrayList.add("sticker/glasses/32.webp");
        arrayList.add("sticker/glasses/33.webp");
        arrayList.add("sticker/glasses/34.webp");
        arrayList.add("sticker/glasses/35.webp");
        arrayList.add("sticker/glasses/36.webp");
        arrayList.add("sticker/glasses/37.webp");
        arrayList.add("sticker/glasses/38.webp");
        arrayList.add("sticker/glasses/39.webp");
        arrayList.add("sticker/glasses/40.webp");
        arrayList.add("sticker/glasses/41.webp");
        arrayList.add("sticker/glasses/42.webp");
        arrayList.add("sticker/glasses/43.webp");
        arrayList.add("sticker/glasses/44.webp");
        arrayList.add("sticker/glasses/45.webp");
        arrayList.add("sticker/glasses/46.webp");
        arrayList.add("sticker/glasses/47.webp");
        return arrayList;
    }

    public static List<String> lstBeards() {
        List<String> arrayList = new ArrayList<>();
        arrayList.add("sticker/beard/b1.webp");
        arrayList.add("sticker/beard/b2.webp");
        arrayList.add("sticker/beard/b3.webp");
        arrayList.add("sticker/beard/b4.webp");
        arrayList.add("sticker/beard/b5.webp");
        arrayList.add("sticker/beard/b6.webp");
        arrayList.add("sticker/beard/b7.webp");
        arrayList.add("sticker/beard/b8.webp");
        arrayList.add("sticker/beard/b9.webp");
        arrayList.add("sticker/beard/b10.webp");
        arrayList.add("sticker/beard/b11.webp");
        arrayList.add("sticker/beard/b12.webp");
        arrayList.add("sticker/beard/b13.webp");
        arrayList.add("sticker/beard/b14.webp");
        arrayList.add("sticker/beard/b15.webp");
        arrayList.add("sticker/beard/b16.webp");
        arrayList.add("sticker/beard/b17.webp");
        arrayList.add("sticker/beard/b18.webp");
        arrayList.add("sticker/beard/b19.webp");
        arrayList.add("sticker/beard/b20.webp");
        arrayList.add("sticker/beard/b21.webp");
        arrayList.add("sticker/beard/b22.webp");
        arrayList.add("sticker/beard/b23.webp");
        arrayList.add("sticker/beard/b24.webp");
        arrayList.add("sticker/beard/b25.webp");
        return arrayList;
    }

    public static List<String> lstTatoos() {
        List<String> arrayList = new ArrayList<>();
        arrayList.add("sticker/tatoo/01.webp");
        arrayList.add("sticker/tatoo/02.webp");
        arrayList.add("sticker/tatoo/03.webp");
        arrayList.add("sticker/tatoo/04.webp");
        arrayList.add("sticker/tatoo/05.webp");
        arrayList.add("sticker/tatoo/06.webp");
        arrayList.add("sticker/tatoo/07.webp");
        arrayList.add("sticker/tatoo/08.webp");
        arrayList.add("sticker/tatoo/09.webp");
        arrayList.add("sticker/tatoo/10.webp");
        arrayList.add("sticker/tatoo/11.webp");
        arrayList.add("sticker/tatoo/12.webp");
        arrayList.add("sticker/tatoo/13.webp");
        arrayList.add("sticker/tatoo/14.webp");
        arrayList.add("sticker/tatoo/15.webp");
        arrayList.add("sticker/tatoo/16.webp");
        arrayList.add("sticker/tatoo/17.webp");
        arrayList.add("sticker/tatoo/18.webp");
        return arrayList;
    }

    public static List<String> lstEmoj() {
        List<String> arrayList = new ArrayList<>();
        arrayList.add("sticker/emoji/001.webp");
        arrayList.add("sticker/emoji/002.webp");
        arrayList.add("sticker/emoji/003.webp");
        arrayList.add("sticker/emoji/004.webp");
        arrayList.add("sticker/emoji/005.webp");
        arrayList.add("sticker/emoji/006.webp");
        arrayList.add("sticker/emoji/007.webp");
        arrayList.add("sticker/emoji/008.webp");
        arrayList.add("sticker/emoji/009.webp");
        arrayList.add("sticker/emoji/010.webp");
        arrayList.add("sticker/emoji/011.webp");
        arrayList.add("sticker/emoji/012.webp");
        arrayList.add("sticker/emoji/013.webp");
        arrayList.add("sticker/emoji/014.webp");
        arrayList.add("sticker/emoji/015.webp");
        arrayList.add("sticker/emoji/016.webp");
        arrayList.add("sticker/emoji/017.webp");
        arrayList.add("sticker/emoji/018.webp");
        arrayList.add("sticker/emoji/019.webp");
        arrayList.add("sticker/emoji/020.webp");
        arrayList.add("sticker/emoji/021.webp");
        arrayList.add("sticker/emoji/022.webp");
        arrayList.add("sticker/emoji/023.webp");
        arrayList.add("sticker/emoji/024.webp");
        arrayList.add("sticker/emoji/025.webp");
        arrayList.add("sticker/emoji/026.webp");
        arrayList.add("sticker/emoji/027.webp");
        arrayList.add("sticker/emoji/028.webp");
        arrayList.add("sticker/emoji/029.webp");
        arrayList.add("sticker/emoji/030.webp");
        arrayList.add("sticker/emoji/031.webp");
        arrayList.add("sticker/emoji/032.webp");
        arrayList.add("sticker/emoji/033.webp");
        arrayList.add("sticker/emoji/034.webp");
        arrayList.add("sticker/emoji/035.webp");
        arrayList.add("sticker/emoji/036.webp");
        arrayList.add("sticker/emoji/037.webp");
        arrayList.add("sticker/emoji/038.webp");
        arrayList.add("sticker/emoji/039.webp");
        arrayList.add("sticker/emoji/040.webp");
        arrayList.add("sticker/emoji/041.webp");
        arrayList.add("sticker/emoji/042.webp");
        arrayList.add("sticker/emoji/043.webp");
        arrayList.add("sticker/emoji/044.webp");
        arrayList.add("sticker/emoji/045.webp");
        arrayList.add("sticker/emoji/046.webp");
        arrayList.add("sticker/emoji/047.webp");
        arrayList.add("sticker/emoji/048.webp");
        arrayList.add("sticker/emoji/049.webp");
        arrayList.add("sticker/emoji/050.webp");
        arrayList.add("sticker/emoji/051.webp");
        arrayList.add("sticker/emoji/052.webp");
        arrayList.add("sticker/emoji/053.webp");
        arrayList.add("sticker/emoji/054.webp");
        arrayList.add("sticker/emoji/055.webp");
        arrayList.add("sticker/emoji/056.webp");
        arrayList.add("sticker/emoji/057.webp");
        arrayList.add("sticker/emoji/058.webp");
        arrayList.add("sticker/emoji/058.webp");
        arrayList.add("sticker/emoji/060.webp");
        arrayList.add("sticker/emoji/063.webp");
        arrayList.add("sticker/emoji/077.webp");
        arrayList.add("sticker/emoji/084.webp");
        arrayList.add("sticker/emoji/085.webp");
        arrayList.add("sticker/emoji/105.webp");
        arrayList.add("sticker/emoji/111.webp");
        arrayList.add("sticker/emoji/112.webp");
        arrayList.add("sticker/emoji/114.webp");
        arrayList.add("sticker/emoji/120.webp");
        arrayList.add("sticker/emoji/131.webp");
        arrayList.add("sticker/emoji/134.webp");
        arrayList.add("sticker/emoji/135.webp");
        arrayList.add("sticker/emoji/136.webp");
        arrayList.add("sticker/emoji/157.webp");
        arrayList.add("sticker/emoji/168.webp");
        arrayList.add("sticker/emoji/169.webp");
        arrayList.add("sticker/emoji/170.webp");
        arrayList.add("sticker/emoji/171.webp");
        arrayList.add("sticker/emoji/172.webp");
        arrayList.add("sticker/emoji/174.webp");
        arrayList.add("sticker/emoji/175.webp");
        arrayList.add("sticker/emoji/177.webp");
        arrayList.add("sticker/emoji/179.webp");
        arrayList.add("sticker/emoji/182.webp");
        arrayList.add("sticker/emoji/183.webp");
        arrayList.add("sticker/emoji/184.webp");
        arrayList.add("sticker/emoji/188.webp");
        arrayList.add("sticker/emoji/190.webp");
        return arrayList;
    }


    public static Bitmap loadBitmapFromAssets(Context context, String str) {
        InputStream inputStream;
        try {
            inputStream = context.getAssets().open(str);
            Bitmap decodeStream = BitmapFactory.decodeStream(inputStream);
            inputStream.close();
            return decodeStream;
        } catch (Exception e) {
            return null;
        }
    }
}
